package com.moha.moss;


import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Yitbarek
 */
public class Landing extends javax.swing.JFrame {
    Set<Integer> seenMessages = new HashSet<>();
     String username, role, dep, Request_File_Path, Check_File_Path, Check_File_Name;
     Message selectedMessage;
     File pdfFile_Name;
     Vector<String> comboBoxData = new Vector<>();
     DatabaseService dbService = new DatabaseService();
     Supporter a = new Supporter();
     List<String> User_Detail;
     DefaultListModel<Message> listModel;
     

    /**
     * Creates new form Landing
     * @param username
     */
    public Landing(String username) {
        this.username = username;
        initComponents();   
        users(username);
        setLocationRelativeTo(null);
    }
    
public void users(String username){
    DatabaseService b = new DatabaseService();
    User_Detail = b.userDetail(username);
    role = User_Detail.get(0);
    dep = User_Detail.get(1);
                       
    if (role.equals("user")) {
        Role.setText("USER");
        Reject_Button.setVisible(false);
        Approve_Button.setVisible(false);
        }
     else if (role.equals("head")) {
        Role.setText("HEAD");}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        signout_Button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        DatabaseService b = new DatabaseService();
        User_Detail = b.userDetail(username);
        String role = User_Detail.get(0);
        String dep = User_Detail.get(1);

        //DefaultListModel<Message> listModel;
        listModel = new javax.swing.DefaultListModel<Message>();
        Inbox = new javax.swing.JList<Message>(listModel);
        messageTextArea = new javax.swing.JTextField();
        sendMessageButton = new javax.swing.JButton();
        MIS = new javax.swing.JRadioButton();
        HR = new javax.swing.JRadioButton();
        PROC = new javax.swing.JRadioButton();
        MARK = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        MG = new javax.swing.JRadioButton();
        FC = new javax.swing.JRadioButton();
        QC = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        String sql1 = "SELECT department FROM departments";
        try{
            DatabaseService a = new DatabaseService();
            try(Connection conn = a.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql1);)
            {
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String deps = rs.getString(1);
                    comboBoxData.add(deps);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Request_Combo = new javax.swing.JComboBox<>(comboBoxData);
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AttachBtn = new javax.swing.JButton();
        RequestButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RequestFilePath_Field = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        RequestNote = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        From_Label = new javax.swing.JLabel();
        PreviewButton = new javax.swing.JButton();
        FileName_Label = new javax.swing.JLabel();
        Reject_Button = new javax.swing.JButton();
        Approve_Button = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TS_Label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Note_Area = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        To_Label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Verdict_Label = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CheckFileName_Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CheckFilePath_Area = new javax.swing.JTextArea();
        Attach2 = new javax.swing.JButton();
        Check_Button = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        Description_Area = new javax.swing.JTextArea();
        Description_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOSS");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MOHA.jpg"))); // NOI18N
        jLabel1.setText("MOHA Office Solution Suit - MOSS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Welcome, "+username);

        Role.setBackground(new java.awt.Color(255, 255, 255));
        Role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Role.setForeground(new java.awt.Color(102, 0, 102));
        Role.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Role.setText("---");

        signout_Button.setBackground(new java.awt.Color(0, 0, 204));
        signout_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signout_Button.setForeground(new java.awt.Color(255, 255, 255));
        signout_Button.setText("Log Out");
        signout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signout_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signout_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Role, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(signout_Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setEnabled(false);

        Inbox.setCellRenderer(new MessageCellRenderer());
        Inbox.setModel(listModel);
        Supporter c = new Supporter();
        Timer timer = new Timer(5000, e -> {
            Message selectedValue = Inbox.getSelectedValue();
            try{
                List<Message> newMessages = b.fetchMessages(role, username, dep);
                boolean hasUnreadMessages = false;

                if (newMessages != null) {
                    for (Message message : newMessages) {

                        if (!seenMessages.contains(message.getMessageId())) {
                            seenMessages.add(message.getMessageId());
                            if (!message.isRead()) {
                                hasUnreadMessages = true;
                            }

                            listModel.add(0, message);
                        }
                    }

                    if (hasUnreadMessages) {
                        c.playNotificationSound();
                    }
                }

                if (selectedValue != null && listModel.contains(selectedValue)) {
                    Inbox.setSelectedValue(selectedValue, true);
                }
            }
            catch (Exception exe) {
            }

        });

        timer.start();
        Inbox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Inbox.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                InboxValueChanged(evt);
            }
        });
        Inbox.setFixedCellHeight(20);
        jScrollPane5.setViewportView(Inbox);

        sendMessageButton.setBackground(new java.awt.Color(0, 0, 204));
        sendMessageButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        sendMessageButton.setForeground(new java.awt.Color(255, 255, 255));
        sendMessageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/broadcast.png"))); // NOI18N
        sendMessageButton.setText("Send");
        sendMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageButtonActionPerformed(evt);
            }
        });

        MIS.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(MIS);
        MIS.setText("MIS");
        MIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISActionPerformed(evt);
            }
        });

        HR.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(HR);
        HR.setText("HR");

        PROC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(PROC);
        PROC.setText("Procurement");
        PROC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROCActionPerformed(evt);
            }
        });

        MARK.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(MARK);
        MARK.setText("Marketing");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inbox.png"))); // NOI18N
        jLabel6.setText("Inbox");

        MG.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(MG);
        MG.setText("Management");

        FC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(FC);
        FC.setText("Finance");

        QC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(QC);
        QC.setText("Quality Control");
        QC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(messageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendMessageButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(MIS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PROC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MARK))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(QC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MG)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MIS)
                    .addComponent(HR)
                    .addComponent(PROC)
                    .addComponent(MARK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QC)
                    .addComponent(FC)
                    .addComponent(MG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageTextArea)
                    .addComponent(sendMessageButton))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Upload :");

        Request_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Request_ComboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("To :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stamp.png"))); // NOI18N
        jLabel10.setText("Digital Stamp");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Note :");

        AttachBtn.setBackground(new java.awt.Color(0, 0, 255));
        AttachBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        AttachBtn.setForeground(new java.awt.Color(255, 255, 255));
        AttachBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attach.png"))); // NOI18N
        AttachBtn.setText("Attach");
        AttachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachBtnActionPerformed(evt);
            }
        });

        RequestButton.setBackground(new java.awt.Color(255, 0, 0));
        RequestButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RequestButton.setForeground(new java.awt.Color(255, 255, 255));
        RequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/request.png"))); // NOI18N
        RequestButton.setText("Request");
        RequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestButtonActionPerformed(evt);
            }
        });

        RequestFilePath_Field.setEditable(false);
        RequestFilePath_Field.setColumns(20);
        RequestFilePath_Field.setLineWrap(true);
        RequestFilePath_Field.setRows(5);
        RequestFilePath_Field.setWrapStyleWord(true);
        jScrollPane1.setViewportView(RequestFilePath_Field);

        RequestNote.setColumns(20);
        RequestNote.setRows(5);
        jScrollPane3.setViewportView(RequestNote);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AttachBtn)
                        .addComponent(RequestButton)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addComponent(Request_Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Request_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AttachBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RequestButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("From  :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setText("File :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setText("Note :");

        From_Label.setBackground(new java.awt.Color(255, 255, 255));
        From_Label.setText("---");

        PreviewButton.setBackground(new java.awt.Color(0, 0, 255));
        PreviewButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        PreviewButton.setForeground(new java.awt.Color(255, 255, 255));
        PreviewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
        PreviewButton.setText("Preview");
        PreviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewButtonActionPerformed(evt);
            }
        });

        FileName_Label.setBackground(new java.awt.Color(255, 255, 255));
        FileName_Label.setText("---");

        Reject_Button.setBackground(new java.awt.Color(204, 0, 0));
        Reject_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Reject_Button.setForeground(new java.awt.Color(255, 255, 255));
        Reject_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue.png"))); // NOI18N
        Reject_Button.setText("Reject");
        Reject_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reject_ButtonActionPerformed(evt);
            }
        });

        Approve_Button.setBackground(new java.awt.Color(0, 153, 0));
        Approve_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Approve_Button.setForeground(new java.awt.Color(255, 255, 255));
        Approve_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/like.png"))); // NOI18N
        Approve_Button.setText("Approve");
        Approve_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Approve_ButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.png"))); // NOI18N
        jLabel15.setText("Messages & Requests");

        TS_Label.setBackground(new java.awt.Color(255, 255, 255));
        TS_Label.setText("---");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel13.setText("Time Stamp  :");

        Note_Area.setEditable(false);
        Note_Area.setColumns(20);
        Note_Area.setLineWrap(true);
        Note_Area.setRows(5);
        Note_Area.setWrapStyleWord(true);
        jScrollPane4.setViewportView(Note_Area);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel14.setText("To  :");

        To_Label.setBackground(new java.awt.Color(255, 255, 255));
        To_Label.setText("---");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FileName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(Approve_Button)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Reject_Button)))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(TS_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 15, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(From_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(To_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15))))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(PreviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TS_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(From_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(To_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FileName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PreviewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reject_Button)
                    .addComponent(Approve_Button))
                .addGap(56, 56, 56))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        Verdict_Label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Verdict_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Verdict_Label.setText("---");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        jLabel17.setText("Check Authentic Document");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel18.setText("File Path :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel19.setText("File Name :");

        CheckFileName_Label.setBackground(new java.awt.Color(255, 255, 255));
        CheckFileName_Label.setText("---");

        CheckFilePath_Area.setEditable(false);
        CheckFilePath_Area.setColumns(20);
        CheckFilePath_Area.setLineWrap(true);
        CheckFilePath_Area.setRows(5);
        CheckFilePath_Area.setWrapStyleWord(true);
        jScrollPane2.setViewportView(CheckFilePath_Area);

        Attach2.setBackground(new java.awt.Color(0, 0, 255));
        Attach2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Attach2.setForeground(new java.awt.Color(255, 255, 255));
        Attach2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attach.png"))); // NOI18N
        Attach2.setText("Attach");
        Attach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attach2ActionPerformed(evt);
            }
        });

        Check_Button.setBackground(new java.awt.Color(204, 0, 0));
        Check_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Check_Button.setForeground(new java.awt.Color(255, 255, 255));
        Check_Button.setText("Check");
        Check_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_ButtonActionPerformed(evt);
            }
        });

        Description_Area.setColumns(20);
        Description_Area.setLineWrap(true);
        Description_Area.setRows(5);
        Description_Area.setWrapStyleWord(true);
        jScrollPane6.setViewportView(Description_Area);

        Description_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Description_Label.setText("Description :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CheckFileName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Verdict_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Description_Label)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Attach2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(CheckFileName_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Attach2)
                    .addComponent(Check_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Description_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Verdict_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachBtnActionPerformed
        
 if (evt.getSource() == AttachBtn) {
    JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter pdfFilter = new FileNameExtensionFilter("PDF Files", "pdf");
    fileChooser.setFileFilter(pdfFilter);
    int res = fileChooser.showOpenDialog(null); 
    if (res == JFileChooser.APPROVE_OPTION) {
        File Request_file = fileChooser.getSelectedFile();
        Request_File_Path = Request_file.getAbsolutePath();
        RequestFilePath_Field.setText(Request_File_Path);
    }
}

    }//GEN-LAST:event_AttachBtnActionPerformed

    private void RequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestButtonActionPerformed
    String department = (String) Request_Combo.getSelectedItem();
    String note = RequestNote.getText();
    boolean requestSuccess;
    
         try {
                System.out.println(Request_File_Path);
                a.uploadFiles(Request_File_Path);
                requestSuccess = dbService.sendRequest(Request_File_Path, username, department, note, "Request");
                if (requestSuccess) {
                JOptionPane.showMessageDialog(this, "Request sent successfully!");} 
                else {
            JOptionPane.showMessageDialog(this, "Failed to send request.");}   
             } 
         catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error sending request: " + e.getMessage());
    }

    }//GEN-LAST:event_RequestButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void MISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MISActionPerformed

    private void PreviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewButtonActionPerformed
     boolean success = a.downloadANDopenPDF(pdfFile_Name.getName());
       if(success){}
       else{JOptionPane.showMessageDialog(this, "Document not found on server / File format error");}
    }//GEN-LAST:event_PreviewButtonActionPerformed

    private void Reject_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reject_ButtonActionPerformed
        String RejectedMessage = "Document is rejected by " + username;
        try {
            dbService.saveMessage(pdfFile_Name.getName(),"broadcast",username, selectedMessage.getToDept(), RejectedMessage);
            JOptionPane.showMessageDialog(this, "Document Rejected!");
              } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error sending message: " + e.getMessage());
        }
    }//GEN-LAST:event_Reject_ButtonActionPerformed

    private void Approve_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Approve_ButtonActionPerformed
       
        String stampText = "Approved by " + username + " on " +
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        String AppprovedMessage = "Document have been approved and digitally stamped by " + username;

        try {      
            String x = a.addDigitalStamp(pdfFile_Name.getName(), stampText);  
            if(x!=null){            
             dbService.saveMessage(x, "broadcast", username, selectedMessage.getToDept(), AppprovedMessage);
             dbService.saveMessage(x, "broadcast", username, dbService.DeptFetcher(selectedMessage.getUsername()), AppprovedMessage);
             JOptionPane.showMessageDialog(this, "Document Approved!");}
            else{
                JOptionPane.showMessageDialog(this, "Document not found in server");}   
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error sending message: " + e.getMessage());
        } 
    }//GEN-LAST:event_Approve_ButtonActionPerformed

    private void sendMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageButtonActionPerformed
        String message = messageTextArea.getText().trim();
        String recipient = null;

        if (MIS.isSelected()) {
            recipient = MIS.getText();
        } else if (HR.isSelected()) {
            recipient = HR.getText();
        } else if (PROC.isSelected()) {
            recipient = PROC.getText();
        } else if (MARK.isSelected()) {
            recipient = MARK.getText();
        } else if (QC.isSelected()) {
            recipient = QC.getText();
        } else if (MG.isSelected()) {
            recipient = MG.getText();
        } else if (FC.isSelected()) {
            recipient = FC.getText();
        }
        
    if (!message.isEmpty() && recipient!=null) {
        try {
            dbService.saveMessage("NULL", "broadcast", username, recipient, message);
            messageTextArea.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error sending message: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Recipient/Message cannot be empty.");
    }
       
    }//GEN-LAST:event_sendMessageButtonActionPerformed

    private void signout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signout_ButtonActionPerformed
        this.setVisible(false); 
        dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_signout_ButtonActionPerformed

    private void Attach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attach2ActionPerformed
if (evt.getSource() == Attach2) {
    
    JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter pdfFilter = new FileNameExtensionFilter("PDF Files", "pdf");
    fileChooser.setFileFilter(pdfFilter);
    int res = fileChooser.showOpenDialog(null);
    if (res == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        Check_File_Path = file.getAbsolutePath();
        Check_File_Name = file.getName();
        CheckFilePath_Area.setText(Check_File_Path);
        CheckFileName_Label.setText(Check_File_Name);
    }
}   
    }//GEN-LAST:event_Attach2ActionPerformed

    private void PROCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PROCActionPerformed

    private void QCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QCActionPerformed

    private void Request_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Request_ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Request_ComboActionPerformed

    private void InboxValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_InboxValueChanged
        if (!evt.getValueIsAdjusting()) {
            selectedMessage = Inbox.getSelectedValue();
            
            if (selectedMessage == null) {
                return;
            }
                       
        try {
                dbService.markMessagesAsRead(selectedMessage.getMessageId(),username);
                List<Message> newMessages = dbService.fetchMessages(role, username, dep);
                boolean hasUnreadMessages = false;
                Message selectedValue = Inbox.getSelectedValue();

            if (newMessages != null) {
                
            for (Message message : newMessages) {

            if (!seenMessages.contains(message.getMessageId())) {
                seenMessages.add(message.getMessageId());
                
                if (!message.isRead()) {
                    hasUnreadMessages = true;
                }
                listModel.add(0, message);
            }
        }

        if (hasUnreadMessages) {
            a.playNotificationSound();
        }
    }
    
    if (selectedValue != null && listModel.contains(selectedValue)) {
        Inbox.setSelectedValue(selectedValue, true);
    }
            selectedMessage.setRead(true);
            Inbox.repaint();
            }
        catch (Exception ex) {
                Logger.getLogger(Landing.class.getName()).log(Level.SEVERE, null, ex);
            }              
            
            TS_Label.setText(selectedMessage.getTS());
            Note_Area.setText(selectedMessage.getContent());
            To_Label.setText(selectedMessage.getToDept());
            From_Label.setText(selectedMessage.getUsername());
            
            Request_File_Path = selectedMessage.getFile();
            pdfFile_Name = new File(Request_File_Path);
            FileName_Label.setText(pdfFile_Name.getName()); 
        }       
    }//GEN-LAST:event_InboxValueChanged


    private void Check_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_ButtonActionPerformed
        boolean isIntact = a.checkFileIntegrity(Check_File_Path);
        if(isIntact){
            Verdict_Label.setText("MATCH FOUND! / AUTHENTIC!");
            Description_Area.setText("Hash calculated for file: "+ Check_File_Name + " => Hash: "
              + a.calculateFileHash(Check_File_Path)  );
        }
        else{
            Description_Area.setText("Hash calculated for file: "+ Check_File_Name + " => Hash: "
              + a.calculateFileHash(Check_File_Path)  );
            Verdict_Label.setText("NOT MATCH FOUND! / FRAUD!");
        }
    }//GEN-LAST:event_Check_ButtonActionPerformed


    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    // Set the Nimbus look and feel
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Create and display the form
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            String username = "YourUsername"; // Replace with actual username
            new Landing(username).setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Approve_Button;
    private javax.swing.JButton Attach2;
    private javax.swing.JButton AttachBtn;
    private javax.swing.JLabel CheckFileName_Label;
    private javax.swing.JTextArea CheckFilePath_Area;
    private javax.swing.JButton Check_Button;
    private javax.swing.JTextArea Description_Area;
    private javax.swing.JLabel Description_Label;
    private javax.swing.JRadioButton FC;
    private javax.swing.JLabel FileName_Label;
    private javax.swing.JLabel From_Label;
    private javax.swing.JRadioButton HR;
    public javax.swing.JList<Message> Inbox;
    private javax.swing.JRadioButton MARK;
    private javax.swing.JRadioButton MG;
    private javax.swing.JRadioButton MIS;
    private javax.swing.JTextArea Note_Area;
    private javax.swing.JRadioButton PROC;
    private javax.swing.JButton PreviewButton;
    private javax.swing.JRadioButton QC;
    private javax.swing.JButton Reject_Button;
    private javax.swing.JButton RequestButton;
    private javax.swing.JTextArea RequestFilePath_Field;
    private javax.swing.JTextArea RequestNote;
    private javax.swing.JComboBox<String> Request_Combo;
    private javax.swing.JLabel Role;
    private javax.swing.JLabel TS_Label;
    private javax.swing.JLabel To_Label;
    private javax.swing.JLabel Verdict_Label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField messageTextArea;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JButton signout_Button;
    // End of variables declaration//GEN-END:variables
}
