package com.moha.moss;

import java.sql.*;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author Yitbarek
 */
public class Login extends javax.swing.JFrame {
    private static final Preferences prefs = Preferences.userNodeForPackage(Login.class);
    private String savedUsername;

    /**
     * Creates new form landing
     */
    public Login() {
        loadUsername();
        initComponents();
        LoginError.setVisible(false);
        setLocationRelativeTo(null);
    }
    private void saveUsername(String username) {
        prefs.put("username", username);
    }
        private void loadUsername() {
        savedUsername = prefs.get("username", "");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField(savedUsername);
        LoginButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();
        saveUsernameCheckBox = new javax.swing.JCheckBox();
        signup_redirect = new javax.swing.JButton();
        Setup_redirect = new javax.swing.JButton();
        LoginError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOHA Office Solution Suit");
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MOHA.jpg"))); // NOI18N
        jLabel1.setText("MOHA Office Solution Suit - MOSS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password :");

        usernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFieldMouseClicked(evt);
            }
        });
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(0, 0, 204));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setLabel("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Head Office");

        ResetButton.setBackground(new java.awt.Color(255, 0, 0));
        ResetButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        saveUsernameCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        saveUsernameCheckBox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        saveUsernameCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        saveUsernameCheckBox.setText("Save username for next time");
        saveUsernameCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveUsernameCheckBox.setSelected(!savedUsername.isEmpty());
        boolean isUsernameSaved = !savedUsername.isEmpty();
        saveUsernameCheckBox.setSelected(isUsernameSaved);
        usernameField.setEditable(!isUsernameSaved);
        saveUsernameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUsernameCheckBoxActionPerformed(evt);
            }
        });

        signup_redirect.setBackground(new java.awt.Color(204, 255, 204));
        signup_redirect.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        signup_redirect.setForeground(new java.awt.Color(0, 0, 204));
        signup_redirect.setText("click here to Sign-Up");
        signup_redirect.setBorder(null);
        signup_redirect.setBorderPainted(false);
        signup_redirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_redirectActionPerformed(evt);
            }
        });

        Setup_redirect.setBackground(new java.awt.Color(51, 51, 51));
        Setup_redirect.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Setup_redirect.setForeground(new java.awt.Color(255, 255, 255));
        Setup_redirect.setText("click here to SetUp");
        Setup_redirect.setBorder(null);
        Setup_redirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Setup_redirectActionPerformed(evt);
            }
        });

        LoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        LoginError.setText("Invalid username/password combination!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Setup_redirect, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signup_redirect, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveUsernameCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passField)
                            .addComponent(usernameField))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LoginError)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginButton)
                    .addComponent(ResetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveUsernameCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Setup_redirect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signup_redirect))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
                                            
    DatabaseService dbService = new DatabaseService();
    String username = usernameField.getText();
    String password = passField.getText();
    
    String sql0 = "SELECT EmpPass FROM login WHERE EmpUserName = ?";
    
    try (Connection conn = dbService.getConnection();
         PreparedStatement stm = conn.prepareStatement(sql0)) {
        
        stm.setString(1, username);
        try (ResultSet rs = stm.executeQuery()) {
            if (rs.next()) {
                String storedHashedPassword = rs.getString("EmpPass");
                boolean isMatch = Supporter.validatePassword(password, storedHashedPassword);
                if (isMatch) {
                    dispose(); 
                    Landing hpage = new Landing(username);
                    hpage.setVisible(true); 
                    if (saveUsernameCheckBox.isSelected()) {
                        saveUsername(username);
                    }
                } else {
                    LoginError.setVisible(true);
                    passField.setText("");
                }
            } else {
                LoginError.setVisible(true);
                passField.setText("");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace(); 
        JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage());
    }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        usernameField.setText("");
        passField.setText("");
        saveUsernameCheckBox.setSelected(false);
        usernameField.setEditable(true);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void saveUsernameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUsernameCheckBoxActionPerformed
        usernameField.setEditable(!saveUsernameCheckBox.isSelected());
    }//GEN-LAST:event_saveUsernameCheckBoxActionPerformed

    private void usernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFieldMouseClicked
         if (!usernameField.isEditable()) {
            usernameField.transferFocus();
        }
    }//GEN-LAST:event_usernameFieldMouseClicked

    private void signup_redirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_redirectActionPerformed
        dispose();  
        SignUp signup_frame = new SignUp();
        signup_frame.show();
    }//GEN-LAST:event_signup_redirectActionPerformed

    private void Setup_redirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Setup_redirectActionPerformed
        //dispose();  
        Setup setup_frame = new Setup();
        setup_frame.show();
    }//GEN-LAST:event_Setup_redirectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginError;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton Setup_redirect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passField;
    private javax.swing.JCheckBox saveUsernameCheckBox;
    private javax.swing.JButton signup_redirect;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

}
