package com.moha.moss;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yitbarek
 */
public class SignUp extends javax.swing.JFrame {
    Vector<String> comboBoxData = new Vector<>();
    private static final Map<String, String> departmentAbbreviations = new HashMap<>();

    static {
        departmentAbbreviations.put("MIS", "mis");
        departmentAbbreviations.put("HR", "hr");
        departmentAbbreviations.put("Procurment", "proc");
        departmentAbbreviations.put("Marketing", "mkt");
        departmentAbbreviations.put("Quality Control", "qcont");
        departmentAbbreviations.put("Finance", "fnc");
        departmentAbbreviations.put("Managment", "mgt");
    }

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_02 = new javax.swing.JPanel();
        SignUp_Label = new javax.swing.JLabel();
        First_Name_Label = new javax.swing.JLabel();
        Department_Label = new javax.swing.JLabel();
        String sql1 = "SELECT department FROM departments";
        try{
            DatabaseService a = new DatabaseService();
            try(Connection conn = a.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql1);)
            {
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String deps = rs.getString(1);
                    comboBoxData.add(deps);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Department_Combo = new javax.swing.JComboBox<>(comboBoxData);
        First_Name_Field = new javax.swing.JTextField();
        Password_Label = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        Register_Button = new javax.swing.JButton();
        Panel_01 = new javax.swing.JPanel();
        MOHA_Label = new javax.swing.JLabel();
        tabela1 = new javax.swing.JLabel();
        tabela2 = new javax.swing.JLabel();
        Login_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        Panel_02.setBackground(new java.awt.Color(204, 204, 204));
        Panel_02.setForeground(new java.awt.Color(153, 153, 153));

        SignUp_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUp_Label.setForeground(new java.awt.Color(0, 0, 0));
        SignUp_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_Label.setText("Sign-Up");

        First_Name_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        First_Name_Label.setForeground(new java.awt.Color(0, 0, 0));
        First_Name_Label.setText("First Name :");

        Department_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Department_Label.setForeground(new java.awt.Color(0, 0, 0));
        Department_Label.setText("Department :");

        Password_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password_Label.setForeground(new java.awt.Color(0, 0, 0));
        Password_Label.setText("Password :");

        Register_Button.setBackground(new java.awt.Color(51, 51, 255));
        Register_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Register_Button.setForeground(new java.awt.Color(255, 255, 255));
        Register_Button.setText("Register");
        Register_Button.setBorderPainted(false);
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });

        Panel_01.setBackground(new java.awt.Color(255, 255, 255));
        Panel_01.setPreferredSize(new java.awt.Dimension(0, 10));

        MOHA_Label.setBackground(new java.awt.Color(255, 255, 255));
        MOHA_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MOHA_Label.setForeground(new java.awt.Color(0, 0, 153));
        MOHA_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MOHA_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MOHA.jpg"))); // NOI18N
        MOHA_Label.setText("MOHA Office Solution Suit - MOSS");

        javax.swing.GroupLayout Panel_01Layout = new javax.swing.GroupLayout(Panel_01);
        Panel_01.setLayout(Panel_01Layout);
        Panel_01Layout.setHorizontalGroup(
            Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MOHA_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );
        Panel_01Layout.setVerticalGroup(
            Panel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_01Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(MOHA_Label))
        );

        tabela1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabela1.setForeground(new java.awt.Color(0, 102, 0));
        tabela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tabela2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Login_Button.setBackground(new java.awt.Color(204, 0, 0));
        Login_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button.setText("Log-In");
        Login_Button.setBorderPainted(false);
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_02Layout = new javax.swing.GroupLayout(Panel_02);
        Panel_02.setLayout(Panel_02Layout);
        Panel_02Layout.setHorizontalGroup(
            Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_01, javax.swing.GroupLayout.PREFERRED_SIZE, 379, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_02Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SignUp_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_Button))
            .addGroup(Panel_02Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_02Layout.createSequentialGroup()
                        .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Department_Label)
                            .addComponent(Password_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Register_Button)
                            .addComponent(Department_Combo, 0, 176, Short.MAX_VALUE)
                            .addComponent(Password_Field)))
                    .addGroup(Panel_02Layout.createSequentialGroup()
                        .addComponent(First_Name_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(First_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(Panel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabela1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabela2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_02Layout.setVerticalGroup(
            Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_02Layout.createSequentialGroup()
                .addComponent(Panel_01, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Login_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SignUp_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name_Label)
                    .addComponent(First_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department_Label)
                    .addComponent(Department_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password_Label)
                    .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Register_Button)
                .addGap(18, 18, 18)
                .addComponent(tabela1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabela2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
         dispose();  
        Login login_frame = new Login();
         login_frame.show();
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
    String firstName = First_Name_Field.getText().trim();
    String department = (String) Department_Combo.getSelectedItem();
    String password = new String(Password_Field.getPassword());

    String departmentAbbrev = departmentAbbreviations.get(department);
    String username = firstName + "@" + departmentAbbrev;
    
    DatabaseService x = new DatabaseService();
        try {
            if(x.signup(department, username, Supporter.hashPassword(password))){
                tabela1.setText("SUCCESFULLY REGISTERED");
                tabela2.setText("Your username is " + username);}
                 else{
                tabela1.setText("Problem Encountred!");
                tabela2.setText("Remember One account per user only!");}        
        } catch (Exception ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_Register_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Department_Combo;
    private javax.swing.JLabel Department_Label;
    private javax.swing.JTextField First_Name_Field;
    private javax.swing.JLabel First_Name_Label;
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel MOHA_Label;
    private javax.swing.JPanel Panel_01;
    private javax.swing.JPanel Panel_02;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JButton Register_Button;
    private javax.swing.JLabel SignUp_Label;
    private javax.swing.JLabel tabela1;
    private javax.swing.JLabel tabela2;
    // End of variables declaration//GEN-END:variables
}
